### ISSUE TITLE
File I/O Error in Create Mesh

### ISSUE THREAD

**Issue by agirault** [nirfast-admin/NIRFAST#7]
Get the following error when launching the Create Mesh:

```
File I/O Error: No such file or directory /path/to/nirfast_mesh/._out.mesh
```

Slicer error log shows the following:

```
ERROR: Command execution failed. Error using OpenFile (line 10)

Error in readMEDIT (line 4)
fid = OpenFile(fn,'rt');

Error in RunCGALMeshGenerator (line 75)
[e p] = readMEDIT(tmpmeshfn);

Error in Image2Mesh (line 109)
    [e p] = RunCGALMeshGenerator(mask,param);
```

When going in `RunCGALMeshGenerator` and debugging before the call to `readMEDIT`, it looks like the call to `image2mesh_cgal-mac64` fails, with the following error:

```
_readImageHeaderAndGetError: an error occurs when reading image
     from file '/Users/alexis/Desktop/test/._cgal_mesher.inr' using format 'Inrimage'
Assertion failed: (px != 0), function operator->, file /usr/local/include/boost/smart_ptr/shared_ptr.hpp, line 418.
 "/Users/alexis/Projects/Dartmouth/nirfastslicer-rel/S-bld/Slicer-build/lib/Slicer-4.5/NIRFASTMatlab/toolbox/meshing/image2mesh_cgal/image2mesh_cgal-mac64.exe" "/Users/alexis/Desktop/test/._cgal_mesher.inr" "/Users/alexis/Desktop/test/._criteria.txt" "/Users/alexis/Desktop/test/._out.mesh": Aborted
```

As a result, no ._out.mesh file has been created by CGAL. Both ._criteria.txt and ._cgal_mesher.inr are present, with the following values:

**criteria.txt**

```
25.000000
1.485000
3.000000
3.000000
1.485000
0
0.000000
```

**cgal_mesher.inr**

```
#INRIMAGE-4#{
XDIM=345
YDIM=268
ZDIM=176
VDIM=1
TYPE=unsigned fixed
PIXSIZE=8 bits
SCALE=2**0
CPU=decm
VX=-0.742000
VY=-0.742500
VZ=1.000000
#GEOMETRY=CARTESIAN
-- there actually is 90 empty lines here --
##}
```

Is is interesting to note that there are 90 empty lines in the inr file.

**Comment by rodinasophie** [comment]
Hello,

I tried to run Nirfast and got the same isssue, how is it possible to solve it?

**Comment by swojtkiewicz** [comment]
Hi,
please see the negative voxel dimensions in your *.inr file:
`VX=-0.742000
VY=-0.742500`
There is a bug/issue in the `Image2Mesh.m` file which makes this values negative. Cutting long story short, there is a problem with conversion from pixel/image coordinates to patient/real world coordinates. Negative values cause a fail of the `RunCGALMeshGenerator.m` and there is no `._out.mesh` file to read by the `readMEDIT` function in the next line after invoking the  `image2mesh_cgal-mac64.exe`.

**Solution:** 
Please edit the `Image2Mesh.m` file located in the Slicer installation folder e.g. `\NIRFASTSlicer 1.0.0\lib\Slicer-4.5\matlab-modules\`. Please make a copy just in case :)
Merge my code below with the file.

```
% Volume Information
param.AnatomicalOrientation = 'LPS' % 'LPI'
param.CenterOfRotation = [0,0,0];
param.NumberOfDimensions = str2num(img.metaData.dimension); % 3
dim = sscanf(img.metaData.sizes, '%f')';
param.Dimensions = dim; % [103,115,130]
offset = strrep(img.metaData.space_origin,'(',' ');
offset = strrep(offset,',',' ');
offset = strrep(offset,')',' ');
offset = sscanf(offset, '%f')';
param.Offset = offset; % [126.9220,2.6726,-78.2673]
% TODO : correct transform
%% USE TRANSFROMATION MATRIX 2 CALCULATE VOXEL DIMENSIONS
% BLOCK changed by S. Wojtkiewicz
% spacedir is equal to img.ijkToLpsTransform(1:3,1:3) (see the nrrdread.mat file)
param.TransformMatrix = img.ijkToLpsTransform;
spacedir = param.TransformMatrix(1:3,1:3);
x = sqrt(sum(spacedir(:,1).^2));%spacedir(1,1)*param.TransformMatrix(1,1);
y = sqrt(sum(spacedir(:,2).^2));%spacedir(2,2)*param.TransformMatrix(2,2);
z = sqrt(sum(spacedir(:,3).^2));%spacedir(3,3)*param.TransformMatrix(3,3);
param.PixelDimensions(1) = x; %(0.73884);
param.PixelDimensions(2) = y; %(0.73884);
param.PixelDimensions(3) = z; %(1)
param.PixelSpacing(1) = x; %(0.73884);
param.PixelSpacing(2) = y; %(0.73884);
param.SliceThickness  = z; %(1);

% Use the transformation matrix to position sources and detectors.
sdcoords = ((spacedir.*[-1 0 0;0 -1 0; 0 0 1])*sdcoords')';

% Mesh Parameters
minsize = min(x, min(y,z));
```
Please look at an extra bit of code `sdcoords = ((spacedir.*[-1 0 0;0 -1 0; 0 0 1])*sdcoords')';`. I have solved another issue here. The original code does not transform the source-detector coordinates at all. Now they are in the patient/real world coordinates.

After all of this you might bump into a next error connected with mismatch of the data type of the *.inr file and data type used by the CGAL library for labeled 3D images. You can spot the error by noisy and strangely (in some regular way) deformed meshes. Correction of this error is out of scope of this post :)

Pozdrawiam

**Comment by mmastand** [comment]
I am having a similar issue when running the image2mesh_gui on Nirfast 9. 

**criteria.txt**
```
25.000000
10.000000
5.000000
3.000000
10.000000
0
0.000000

```

and the **cgal_mesher.inr**
```
#INRIMAGE-4#{
XDIM=80
YDIM=157
ZDIM=157
VDIM=1
TYPE=unsigned fixed
PIXSIZE=8 bits
SCALE=2**0
CPU=decm
VX=1.000000
VY=1.000000
VZ=1.000000
#GEOMETRY=CARTESIAN

%% 90 lines of white space%%

##}

I'm not having a problem with the negative pixel spacing, but the output mesh file is never being written. It's failing in line 72 of RunCGALMeshGenerator:
```
eval(makemeshcommand)
```
which is the cgal executable. I assume it's from the set up because I am able to make meshes out of the slicer interface without an issue. I'm running this in MacOS, though I saw the same problem on Windows 10. 

Alternatively, is there a way to control the tetrahedron size in a 3D mesh out of slicer? Hi Scott!

**Comment by agirault** [comment]
@rodinasophie, @swojtkiewicz, sorry for the delay and the inconvenience.
We have fixed the issue and have been testing it cross-platform, it is similar to stanislaw solution. We plan to make a new release soon including the fix and a couple enhancements.

Thank you.
