### ISSUE TITLE
Slicer loads all values from *.vtk files as zeros

### ISSUE THREAD

**Issue by swojtkiewicz** [nirfast-admin/NIRFAST#8]
Hi,
I want to overlap DICOM data and Nirfast simulation results (optical properties) saved in a `*.vtk` file.
The file generated by `nirfast2vtk.m` has no errors (a proper formatting and proper data values) according to [the format specification](http://www.vtk.org/wp-content/uploads/2015/04/file-formats.pdf).
Importing optical properties into the Slicer does not rise any errors. All is loaded (region, kappa, mua, mus, etc.). However, all values of the loaded properties are 0. Actually there is only one value (0) in the `*.nrrd` files generated by the Slicer after reading the `*.vtk` file.
I have tried to change the `*.vtk` file in almost every possible way (different carriage returns, data formats, data string representation, etc.). Hoping I will guess the possible mistake in parsing the `*.vtk` file in Slicer.
I think there might be a problem with a conversion from mesh-like data (`*.vtk`) to pixel-like data (`*.nrrd`) inside the _NIRFASTSlicer_.
As a temporary workaround I convert the mesh-based Nirfast results to a pixel-based `*.nrrd` file using my Matlab script. I can load this file into the Slicer and overlap it with a DICOM image.

Can someone confirm the problem and check what is the source of it?

**Comment by agirault** [comment]
Hello Stanislaw,

Could you attach your `vtk` file here? Your `nrrd` file and your Matlab script could be useful too. We'll look at it and do some testing to find what the issue is.

_Also, you could try visualizing your `vtk` file in [Paraview](http://www.paraview.org/) directly to see if the information is well represented as a mesh._

Thank you.

**Comment by agirault** [comment]
Feel free to answer back if you still need help with this.
