### ISSUE TITLE
Can NIRFAST slicer work for 2D image?

### ISSUE THREAD

**Issue by cindyyh** [nirfast-admin/NIRFAST#9]
Can NIRFAST slicer work for single 2D image case? I try to do image crop and segmentation with the slicer, it crashed down every time I tried to crop the image. And if I skip the crop step and go to do segmentation, the label does not work. How can I solve this?

**Comment by agirault** [comment]
Hello @cindyyh. Would you be able to test with [NIRFAST-Slicer 2.0](https://github.com/nirfast-admin/NIRFASTSlicer/releases/tag/v2.0.0) ? Please feel free to answer here and re-open the issue if that doesn't handle your use case.
